//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "auth", table_name = "provider")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub logo_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_provider::Entity")]
    UserProvider,
}

impl Related<super::user_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProvider.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_provider::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_provider::Relation::Provider.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
