//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "auth", table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub name: String,
    pub password: Option<String>,
    pub photo_url: Option<String>,
    pub is_email_verified: bool,
    pub is_two_factor_enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
    #[sea_orm(has_many = "super::user_provider::Entity")]
    UserProvider,
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::user_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProvider.def()
    }
}

impl Related<super::provider::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_provider::Relation::Provider.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_provider::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
